# This file was generated by GoReleaser. DO NOT EDIT.
cask "paperless-ngx-cli" do
  version "1.1.1"

  on_macos do
    on_intel do
      sha256 "8a47f0e0ab757b3665215a8d7d9bc64cd128adf0e240d4574140ad2790099d2f"
      url "https://github.com/stefanhoth/paperless-ngx-cli/releases/download/v#{version}/paperless-ngx-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e62f17dd846990351faf663a8a9455db76ec41a4131b88d5947cb3fdef16d279"
      url "https://github.com/stefanhoth/paperless-ngx-cli/releases/download/v#{version}/paperless-ngx-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "00d5e1eb3f0e745a7ca0a5c33b4e43328b41a87221e0187a4f388eab46b7b95b"
      url "https://github.com/stefanhoth/paperless-ngx-cli/releases/download/v#{version}/paperless-ngx-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a524101902673de2d5e3f29a4ba402ffe07c96a634c6600ee9b62b0882b080d1"
      url "https://github.com/stefanhoth/paperless-ngx-cli/releases/download/v#{version}/paperless-ngx-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "paperless-ngx-cli"
  desc "Paperless-NGX document archive, from the terminal"
  homepage "https://github.com/stefanhoth/paperless-ngx-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "paperless"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/paperless"]
    end
  end

  # No zap stanza required

end
