# This file was generated by GoReleaser. DO NOT EDIT.
cask "paperless-ngx-cli" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "32af8e8e49170c7ec30c71d5ca53b103146d5786817ad278f9c3abee89326498"
      url "https://github.com/stefanhoth/paperless-ngx-cli/releases/download/v#{version}/paperless-ngx-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "681558d216c4c5d5750bb2f48d4646553b29c481d68ca1aa236b5519a1ffe101"
      url "https://github.com/stefanhoth/paperless-ngx-cli/releases/download/v#{version}/paperless-ngx-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "620f2a0f1da672d9f97558bf7e89b068ef10d4528dc8a575862470633b8baece"
      url "https://github.com/stefanhoth/paperless-ngx-cli/releases/download/v#{version}/paperless-ngx-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3fadcb53d64e0f2b625f9301cb40169b4606e4cd6bafbb823e120f1deec573d2"
      url "https://github.com/stefanhoth/paperless-ngx-cli/releases/download/v#{version}/paperless-ngx-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "paperless-ngx-cli"
  desc "Paperless-NGX document archive, from the terminal"
  homepage "https://github.com/stefanhoth/paperless-ngx-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "paperless"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/paperless"]
    end
  end

  # No zap stanza required

end
