# This file was generated by GoReleaser. DO NOT EDIT.
cask "paperless-ngx-cli" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "ed3c4f143530a83f3692a8efb7c48afd3b16e79cd7dc620d679f8a5914016981"
      url "https://github.com/stefanhoth/paperless-ngx-cli/releases/download/v#{version}/paperless-ngx-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b01d063a71e899aaf3d8c3ae990ee1f38d0bf21f5e15f883b3f7dd3b724da743"
      url "https://github.com/stefanhoth/paperless-ngx-cli/releases/download/v#{version}/paperless-ngx-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f3c3355cf3199c1153a49dfb91c5d57223a66d7db6f5c78f8da1567384d92624"
      url "https://github.com/stefanhoth/paperless-ngx-cli/releases/download/v#{version}/paperless-ngx-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e96ab4e1940993a8cedc9a016b39024c05ddb22fe5a509471c57d1cd662a57ef"
      url "https://github.com/stefanhoth/paperless-ngx-cli/releases/download/v#{version}/paperless-ngx-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "paperless-ngx-cli"
  desc "Paperless-NGX document archive, from the terminal"
  homepage "https://github.com/stefanhoth/paperless-ngx-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "paperless"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/paperless"]
    end
  end

  # No zap stanza required

end
